### PR TITLE
[298] Changed the minimum iOS/macOS/watchOS/tvOS deployment targets to match the .podspec

### PR DESCRIPTION
**Pull request by thad**
**Issue:** https://github.com/carambalabs/SugarRecord/issues/298

### Short description
Changed the minimum iOS/macOS/watchOS/tvOS deployment targets to match the .podspec

### Solution
The minimum deployment target did not match what was defined in the .podspec

### Implementation
Updated all of the minimum deployment targets to match the .podspec

### CODE REVIEW

**Comment by pepibumur** [comment]
@thad great!. Would you mind also matching the versions for the other platforms? Thanks a lot

**Comment by thad** [comment]
@pepibumur Are you talking about tvOSRealm and tvOSCoreData?

**Comment by pepibumur** [comment]
Yeah, all the targets, just match them with the definition in the `.podspec`.
I created an issue related to this to validate that `.podspec` matches the configuration in the Carthage project. Good catch by the way.

**Comment by thad** [comment]
@pepibumur done.

**Pull request merged**
